version: '3.7'

services:
  prosys_angular-prod:
    container_name: prosys_angular
    build:
      context: .
      dockerfile: ./Dockerfile-prod
      network: host
    ports:
      - '4202:80'
    volumes:
      - ./:/app
      - /app/dist
      - /app/node_modules
      - npm-cache:/root/.npm
      - ts-cache:/root/.ts-node
    working_dir: /app

volumes:
  npm-cache:
    driver: local
  ts-cache:
    driver: local
