FROM node:20.9.0-alpine AS builder

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV NODE_OPTIONS="--max_old_space_size=2048"
RUN npm run build:prod

FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
