/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** By addressing to this endpoint you can see whether server alive or not */
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["AuthController_authLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/exams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all exams */
    get: operations["ExamController_getAll"];
    put?: never;
    /** Create exam */
    post: operations["ExamController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/exams/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get exam by id */
    get: operations["ExamController_getById"];
    /** Edit exam by id */
    put: operations["ExamController_editById"];
    post?: never;
    /** Delete exam by id */
    delete: operations["ExamController_deleteById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lessons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all lessons */
    get: operations["LessonController_getAll"];
    put?: never;
    /** Create lesson */
    post: operations["LessonController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lessons/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get lesson by id */
    get: operations["LessonController_getById"];
    /** Edit lesson by id */
    put: operations["LessonController_editById"];
    post?: never;
    /** Delete lesson by id */
    delete: operations["LessonController_deleteById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/students": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all students */
    get: operations["StudentController_getAll"];
    put?: never;
    /** Create student */
    post: operations["StudentController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/students/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get student by id */
    get: operations["StudentController_getById"];
    /** Edit student by id */
    put: operations["StudentController_editById"];
    post?: never;
    /** Delete student by id */
    delete: operations["StudentController_deleteById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CommonResponseClass: {
      statusCode: number;
      message: string;
    };
    LoginDto: {
      login: string;
      password: string;
    };
    LoginResponseClass: {
      accessToken: string;
    };
    ExamDto: {
      /** @description Lesson code (3 characters) */
      lessonCode: string;
      /** @description Student number (up to 5 digits) */
      studentNumber: number;
      /** @description Exam date as UTC timestamp (number) */
      examDate: number;
      /** @description Exam grade (1 digit) */
      grade: number;
    };
    ExamModel: {
      /** Format: uuidV4 */
      id: string;
      lessonCode: string;
      studentNumber: number;
      examDate: string;
      grade: number;
    };
    LessonDto: {
      code: string;
      name: string;
      class: number;
      teacherName: string;
      teacherSurname: string;
    };
    LessonModel: {
      /** Format: uuidV4 */
      id: string;
      code: string;
      name: string;
      class: number;
      teacherName: string;
      teacherSurname: string;
    };
    StudentDto: {
      /** @description Student number (up to 5 digits) */
      number: number;
      /** @description Student first name (up to 30 characters) */
      name: string;
      /** @description Student last name (up to 30 characters) */
      surname: string;
      /** @description Class number (2 digits) */
      class: number;
    };
    StudentModel: {
      /** Format: uuidV4 */
      id: string;
      number: number;
      name: string;
      surname: string;
      class: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  AuthController_authLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponseClass"];
        };
      };
    };
  };
  ExamController_getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExamModel"][];
        };
      };
    };
  };
  ExamController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExamDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  ExamController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of exam (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExamModel"];
        };
      };
    };
  };
  ExamController_editById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of exam (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExamDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  ExamController_deleteById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of exam (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  LessonController_getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LessonModel"][];
        };
      };
    };
  };
  LessonController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LessonDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  LessonController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of lesson (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LessonModel"];
        };
      };
    };
  };
  LessonController_editById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of lesson (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LessonDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  LessonController_deleteById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of lesson (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  StudentController_getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudentModel"][];
        };
      };
    };
  };
  StudentController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StudentDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  StudentController_getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of student (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudentModel"];
        };
      };
    };
  };
  StudentController_editById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of student (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StudentDto"];
      };
    };
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
  StudentController_deleteById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description id of student (uuidV4) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommonResponseClass"];
        };
      };
    };
  };
}
